---
policies:
  - type: commit
    spec:
      header:
        length: 72
        imperative: true
      body:
        required: true
      dco: true
      gpg: true
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - style
          - test
        scopes:
          - deps
          - docker
          - nix
          - policy
