# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
APPLY_FIXES: all # all, none, or list of linter keys.

# Example for key: GIT_GIT_DIFF uncomment to run only that linter.
# ENABLE_LINTERS: [SPELL_CODESPELL]

# Linters that are not supported by cit but enabled for all megalinter images.
DISABLE_LINTERS:
  [
    ACTION_ACTIONLINT,
    C_CPPLINT,
    COPYPASTE_JSCPD,
    CREDENTIALS_SECRETLINT,
    JAVASCRIPT_STANDARD,
    JSON_JSONLINT,
    JSON_ESLINT_PLUGIN_JSONC,
    JSON_V8R,
    JSON_PRETTIER,
    MARKDOWN_MARKDOWNLINT,
    MARKDOWN_MARKDOWN_LINK_CHECK,
    MARKDOWN_MARKDOWN_TABLE_FORMATTER,
    SPELL_MISSPELL,
    YAML_V8R,
  ]

# Policies.
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FAIL_IF_UPDATED_SOURCES: true
FORMATTERS_DISABLE_ERRORS: false

# Reports style.
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false # Enable only if runner has internet connection.
PRINT_ALPACA: false # Don't print logo.

# DEBUG - verbose output of command calls with respective arguments.
# INFO - moderate output with linting statistics.
# ERROR - minimum output only in case of error.
LOG_LEVEL: INFO

# MARKDOWN_REMARK_LINT
MARKDOWN_DEFAULT_STYLE: "remark-lint"
MARKDOWN_REMARK_LINT_CONFIG_FILE: "rc.yaml"

# MARKDOWN_TEXTLINT
MARKDOWN_TEXTLINT_FILTER_REGEX_EXCLUDE: "license.md"

# BASH_EXEC.
ERROR_ON_MISSING_EXEC_BIT: true

# YAML_YAMLLINT.
YAML_YAMLLINT_ARGUMENTS: "-s" # Strict.

# SPELL_CSPELL.
SPELL_CSPELL_CONFIG_FILE: ci/checks/dictionaries/cspell.json
SPELL_CSPELL_FILE_EXTENSIONS: "*"

# # SPELL_CODESPELL.
# SPELL_CODESPELL_ARGUMENTS: >
#   -D=-
#   -D=./ci/checks/dictionaries/spelling_corrections.txt

# CPP_CPPLINT.
CPP_CPPLINT_ARGUMENTS: >
  --recursive
  --linelength=80
  --includeorder=standardcfirst
  --filter=-build/c++11,-build/header_guard,-runtime/references
  --root=./sources
