# yaml-language-server: $schema=https://megalinter.github.io/latest/json-schemas/configuration.html

APPLY_FIXES: none # all, none, or list of linter keys
ENABLE_LINTERS: SPELL_CSPELL,BASH_SHELLCHECK
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
SPELL_CSPELL_CONFIG_FILE: ci/checks/dictionaries/cspell.json