# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
APPLY_FIXES: none # all, none, or list of linter keys.

#  ENABLE_LINTERS: [
#    GIT_GIT_DIFF,
#    SPELL_CSPELL,
#    BASH_SHELLCHECK,
#    CPP_CPPLINT,
#    YAML_YAMLLINT
#  ]

# Linters that are not supported by cit but enabled for all megalinter images.
DISABLE_LINTERS:
  [
    BASH_EXEC,
    BASH_SHFMT,
    C_CPPLINT,
    COPYPASTE_JSCPD,
    CREDENTIALS_SECRETLINT,
    JAVASCRIPT_STANDARD,
    JSON_JSONLINT,
    JSON_ESLINT_PLUGIN_JSONC,
    JSON_V8R,
    JSON_PRETTIER,
    MARKDOWN_MARKDOWNLINT,
    MARKDOWN_MARKDOWN_LINK_CHECK,
    MARKDOWN_MARKDOWN_TABLE_FORMATTER,
    SPELL_MISSPELL,
    YAML_V8R,
  ]

# Policies.
# Disable check of generated .mega-linter.yml:
FILTER_REGEX_EXCLUDE: '(\.github/workflows)'
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FAIL_IF_UPDATED_SOURCES: true

# Reports style.
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false # Enable only if runner has internet connection.
PRINT_ALPACA: false # Don't print logo.

# INFO - statistics output.
# DEBUG - commands with arguments.
# ERROR - error only output.
LOG_LEVEL: INFO

# SPELL_CSPELL.
SPELL_CSPELL_CONFIG_FILE: ci/checks/dictionaries/cspell.json
SPELL_CSPELL_FILE_EXTENSIONS: "*"

# CPP_CPPLINT.
CPP_CPPLINT_ARGUMENTS: >
  --recursive
  --linelength=80
  --includeorder=standardcfirst
  --filter=-build/c++11,-build/header_guard,-runtime/references
  --root=./sources
