---
language: minimal
dist: focal
sudo: required
services: docker
before_install: sudo chmod 777 "$(pwd)"
  && sudo chmod -R 777 "$(pwd)/.git"
install: ./ci/docker/docker_pull.sh
git:
  depth: false

jobs:
  include:
    - name: "Build docker"
      before_install: sudo mkdir -m 0755 /nix
                      && sudo chown travis /nix
      install: curl -L https://nixos.org/nix/install | sh
               && . /home/travis/.nix-profile/etc/profile.d/nix.sh
      script: ./ci/docker/build_with_nix.sh
    - name: "Build docker from docker"
      script: |
        ./ci/docker/docker_run_with_network.sh ./ci/docker/build_with_nix.sh
    - name: "Lint all from nix shell"
      before_install: sudo mkdir -m 0755 /nix
        && sudo chown travis /nix
      install: curl -L https://nixos.org/nix/install | sh
        && . /home/travis/.nix-profile/etc/profile.d/nix.sh
      script: nix-shell --run ./ci/checks/all.sh
    - name: "Lint all in docker from nix shell"
      env: SCRIPT="./ci/checks/all.sh"
      script: ./ci/docker/docker_run_nix_shell.sh ${SCRIPT}
    - name: "Lint all"
      env: SCRIPT="./ci/checks/all.sh"
    - name: "Gcc"
      env: SCRIPT="./ci/builders/gcc/build.sh"
    - name: "Clang"
      env: SCRIPT="./ci/builders/clang/build.sh"

script: ./ci/docker/docker_run.sh ${SCRIPT}
