---
language: minimal
sudo: required
services: docker
before_install: sudo chmod -R 777 "$(pwd)"
install: ./ci/docker/docker_pull.sh
git:
  depth: false

jobs:
  include:
    - name: "Build docker"
      before_install: sudo mkdir -m 0755 /nix
                      && sudo chown travis /nix
      install: curl -L https://nixos.org/nix/install | sh
               && . /home/travis/.nix-profile/etc/profile.d/nix.sh
      script: nix build -f ./ci/nix/docker_build.nix
              --enforce-determinism
              --keep-failed
        && ls -la .
        && sha256sum ./result
    - name: "Lint all from nix shell"
      before_install: sudo mkdir -m 0755 /nix
        && sudo chown travis /nix
      install: curl -L https://nixos.org/nix/install | sh
        && . /home/travis/.nix-profile/etc/profile.d/nix.sh
      script: nix-shell --run ./ci/checks/all.sh
    - name: "Lint all"
      env: SCRIPT="./ci/checks/all.sh"
    - name: "Gcc"
      env: SCRIPT="./ci/builders/gcc/build.sh"
    - name: "Clang"
      env: SCRIPT="./ci/builders/clang/build.sh"

script: ./ci/docker/docker_run.sh ${SCRIPT}
