# SPDX-FileCopyrightText: © 2022 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
coverage:
  precision: 1
  round: nearest
  status:
    project:
      default:
        threshold: 1%
codecov:
  branch: develop
